language: cpp
compiler:
    - gcc
before_install:
    # disable rvm, use system Ruby
    - rvm reset
    - wget https://raw.githubusercontent.com/yast/yast-devtools/SLE-12-GA/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "rake yast2-core yast2-devtools yast2-ruby-bindings" -g "yast-rake"
script:
    - rake check:syntax
    - make -f Makefile.cvs
    - make
    - sudo make install
    - make check

